### ISSUE TITLE
Have a switch to run vita on the actual domain passed to the tool and not the root.

### ISSUE THREAD

**Issue by dee-see** [junnlikestea/vita#28]
Hello! From my understanding of the code, in [here](https://github.com/junnlikestea/vita/blob/7db38da265be317b970e942308ee804affb7f2ac/src/lib.rs#L213), if I call `vita -d a.b.com`, the tool will run on `b.com` pulling all sorts of domains I'm not interested in.

Would you consider a feature to toggle that behavior something interesting for this tool?

**Comment by junnlikestea** [comment]
>the tool will run on `b.com` pulling all sorts of domains I'm not interested in.

Yep that's correct, I extract the tld from each domain in the input and collect data related to that tld.

>Would you consider a feature to toggle that behavior something interesting for this tool?

I think adding a flag similar to assetfinder's `subs-only` would do the trick. I'm a little busy right now but I can probably get to it sometime over the next few days.

**Comment by dee-see** [comment]
It's a little different than `subs-only`, I basically want vita to run on the input and not modify the host because processing. I'll implement something and figure out the name later :P

**Comment by junnlikestea** [comment]
Yea the fix I added won't chop the input down to the root domain anymore, if you've set that flag.
https://github.com/junnlikestea/vita/blob/5e0dc9c270cdb2acda4bdfe6d04ebdd5374e25ed/src/lib.rs#L237-L241

And the output will just be filtered to any subdomain that ends with that input domain
https://github.com/junnlikestea/vita/blob/5e0dc9c270cdb2acda4bdfe6d04ebdd5374e25ed/src/lib.rs#L265

I think that covers what you wanted, but if I've missed something feel free to let me know. Also looking at this now, `roots` might be a poor choice of variable name because if you've selected the `subs-only` flag it's just going to be the list of domains you've provided as input.

**Comment by dee-see** [comment]
LGTM! Thanks!

**Comment by junnlikestea** [comment]
No worries,  thanks for #29  I'll take a look tomorrow!

**Comment by dee-see** [comment]
This isn't Vita's fault, but I noticed that SonarSearch returns results for the root domain even when we send it a subdomain. The output is fine but some `subdomain.amazonaws.com` subdomain made its way in my automation and the results have been coming in for the last 2 hours. I'll see if I can get something in Crobat to fix this issue or if it's sonarsearch itself that does that.

**Comment by dee-see** [comment]
Yeah here's why https://github.com/Cgboal/SonarSearch/blob/3135da3283dcb9c463aca01a0e3924be9c1f499f/crobat-server/server.go#L99 and `GetDomain` comes from here https://github.com/Cgboal/DomainParser/blob/74cdb61e2cdc2b9337b1c50bd39fc7b25320b095/parser.go#L44

**Comment by dee-see** [comment]
I opened https://github.com/Cgboal/SonarSearch/issues/19 to see if they'd like such a feature in the project and how they'd like to see that implemented, then I'll contribute the feature and loop back here so Vita can call that new API when the `--subs-only` switch is set.

**Comment by dee-see** [comment]
SonarSearch fixed their API, no action required here.
